### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'DeepLearningTools'


### ISSUE THREAD

**Issue by gcnonato** [phborba/DeepLearningTools#4]
Impossível carregar complemento 'DeepLearningTools'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 798, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'DeepLearningTools'

```
DeepLearningTools 0.1, QGIS 3.18.0-Zürich on Windows 10

**Comment by phborba** [comment]
Muito obrigado pelo reporte, corrigi na versão mais recente.

Qualquer problema, é só reportar novamente, por gentileza.
